package View;

public class frmMenuUtama extends javax.swing.JFrame {

    /** Creates new form MenuAkademik */
    public frmMenuUtama() {
        initComponents();
        setSize(1000, 600);
        setLocationRelativeTo(this);
        Koneksi.Database.KoneksiDB();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuNasabah = new javax.swing.JMenuItem();
        mnuKeluar = new javax.swing.JMenuItem();
        mnuLaporan = new javax.swing.JMenu();
        mnuLaporanNasabah = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuFile.setText("File");
        mnuFile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        mnuNasabah.setText("Nasabah");
        mnuNasabah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNasabahActionPerformed(evt);
            }
        });
        mnuFile.add(mnuNasabah);

        mnuKeluar.setText("Keluar");
        mnuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKeluarActionPerformed(evt);
            }
        });
        mnuFile.add(mnuKeluar);

        jMenuBar1.add(mnuFile);

        mnuLaporan.setText("Laporan");
        mnuLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLaporanActionPerformed(evt);
            }
        });

        mnuLaporanNasabah.setText("Laporan Daftar Nasabah");
        mnuLaporanNasabah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLaporanNasabahActionPerformed(evt);
            }
        });
        mnuLaporan.add(mnuLaporanNasabah);

        jMenuBar1.add(mnuLaporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuNasabahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNasabahActionPerformed
        View.FrmNasabah objMhs = new View.FrmNasabah();
        objMhs.setLocationRelativeTo(this);
        objMhs.setVisible(true);
}//GEN-LAST:event_mnuNasabahActionPerformed

    private void mnuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKeluarActionPerformed
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        System.exit(0);
    }//GEN-LAST:event_mnuKeluarActionPerformed

    private void mnuLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLaporanActionPerformed

    }//GEN-LAST:event_mnuLaporanActionPerformed

    private void mnuLaporanNasabahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLaporanNasabahActionPerformed

     
    }//GEN-LAST:event_mnuLaporanNasabahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmMenuUtama().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuKeluar;
    private javax.swing.JMenu mnuLaporan;
    private javax.swing.JMenuItem mnuLaporanNasabah;
    private javax.swing.JMenuItem mnuNasabah;
    // End of variables declaration//GEN-END:variables
}


